name: CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        include:
          - TARGET: linux
            os: ubuntu-18.04
          - TARGET: macos
            os: macos-10.15
          - TARGET: windows
            os: windows-latest
    runs-on: ${{ matrix.os }}
    
    defaults:
      run:
        shell: ${{ matrix.os == 'Windows' && 'msys2 {0}' || 'bash' }}
    
    steps:
      - uses: actions/checkout@v2
        with:
          repository: webmproject/libvpx
          
      - uses: msys2/setup-msys2@v2
        if: matrix.TARGET == 'windows'
        with:
          release: false
          install: >-
            base-devel
            git
      
      - name: Install dependencies (macOS)
        if: matrix.TARGET == 'macos'
        run: brew install yasm
        
      - name: Install dependencies (Linux)
        if: matrix.TARGET == 'linux'
        run: sudo apt install yasm
        
      - name: Install dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: python.exe -c "import os; from urllib.request import urlretrieve; urlretrieve('http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe', os.path.join(os.environ['GITHUB_WORKSPACE'], 'yasm.exe'))"
      - name: Add Yasm to PATH (Windows)
        if: matrix.os == 'windows-latest'
        run: echo "$env:GITHUB_WORKSPACE" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        
      - name: Configure build
        run: ./configure --disable-examples --disable-tools --disable-docs --enable-vp9-decoder --disable-vp8-decoder --disable-vp8-encoder --disable-vp9-encoder --disable-unit-tests

      - name: Build
        run: make -j2
        
      - name: Upload temporary artifact (Unix)
        if: matrix.TARGET != 'windows'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.TARGET }}
          path: libvpx.a
          
      - name: Debug
        run: ls
          
      - name: Upload temporary artifact (Windows)
        if: matrix.TARGET == 'windows'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.TARGET }}
          path: vpx.lib
          
  release:
    runs-on: ubuntu-18.04
    name: Publish artifacts to GitHub Releases
    needs: [build]
  
    steps:
      - name: Get tag name
        id: get_tag
        run: echo ::set-output name=TAG::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.TAG }}
          release_name: Release ${{ steps.get_tag.outputs.TAG }}
        
      - name: Download Linux build
        uses: actions/download-artifact@v1
        with:
          name: linux

      - name: Download macOS build
        uses: actions/download-artifact@v1
        with:
          name: macos
          
      - name: Download Windows build
        uses: actions/download-artifact@v1
        with:
          name: windows
          
      - name: Upload macOS package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: macos/libvpx.a
          asset_name: libvpx-macos.a
          asset_content_type: application/x-binary
          
      - name: Upload Linux package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: linux/libvpx.a
          asset_name: libvpx-linux.a
          asset_content_type: application/x-binary
          
      - name: Upload Windows package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: windows/vpx.lib
          asset_name: libvpx-windows.lib
          asset_content_type: application/x-binary
