name: Build libvpx

on:
  push:
    tags:
      - "*"

jobs:
  build:
    strategy:
      matrix:
        include:
          - TARGET: linux
            os: ubuntu-22.04
          - TARGET: macos
            os: macos-11
          - TARGET: windows
            os: windows-2022
    
    runs-on: ${{ matrix.os }}
    
    defaults:
      run:
        shell: ${{ matrix.TARGET == 'windows' && 'msys2 {0}' || 'bash' }}
    
    steps:
      - uses: actions/checkout@v2
        with:
          repository: webmproject/libvpx

      - name: Install msys2
        uses: msys2/setup-msys2@v2
        if: matrix.TARGET == 'windows'

      - name: Check shell
        run: uname -s
      
      - name: Install dependencies (macOS)
        if: matrix.TARGET == 'macos'
        run: brew install yasm
        
      - name: Install dependencies (Linux)
        if: matrix.TARGET == 'linux'
        run: sudo apt install yasm

      - name: Install dependencies (Windows)
        if: matrix.TARGET == 'windows'
        run: pacman -S --noconfirm diffutils make yasm mingw-w64-x86_64-gcc
        
      - name: Create build dir
        run: mkdir build-output
        
      - name: Configure build
        run: cd build-output && ../configure --disable-examples --disable-tools --disable-docs --enable-vp9-decoder --enable-vp8-decoder --disable-vp8-encoder --disable-vp9-encoder --disable-unit-tests

      - name: Check yasm availability
        run: cd build-output && ls && yasm --version

      - name: Build
        run: cd build-output && make -j2
        
      - name: Upload temporary artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.TARGET }}
          path: build-output/libvpx.a
          
  release:
    runs-on: ubuntu-22.04
    name: Publish artifacts to GitHub Releases
    needs: [build]
  
    steps:
      - name: Download Linux build
        uses: actions/download-artifact@v1
        with:
          name: linux

      - name: Download macOS build
        uses: actions/download-artifact@v1
        with:
          name: macos

      - name: Download Windows build
        uses: actions/download-artifact@v1
        with:
          name: windows
          
      - run: mv linux/libvpx.a libvpx-linux.a && mv macos/libvpx.a libvpx-macos.a && mv windows/libvpx.a libvpx-windows.a
    
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: ${{ inputs.releaseName }}
          files: |
            libvpx-linux.a
            libvpx-macos.a
            libvpx-windows.a
